const GET_CURRENT_WEATHER = 'weather/GET_CURRENT_WEATHER'; // user action

// saga actions
const START_GET_CURRENT_WEATHER = 'weather/START_GET_CURRENT_WEATHER';
const STOP_GET_CURRENT_WEATHER = 'weather/STOP_GET_CURRENT_WEATHER';
const GET_CURRENT_WEATHER_SUCCESS = 'weather/GET_CURRENT_WEATHER_SUCCESS';
const GET_CURRENT_WEATHER_FAILED = 'weather/GET_CURRENT_WEATHER_FAILED';

export default {
    GET_CURRENT_WEATHER,
    START_GET_CURRENT_WEATHER,
    STOP_GET_CURRENT_WEATHER,
    GET_CURRENT_WEATHER_SUCCESS,
    GET_CURRENT_WEATHER_FAILED,
};
